let html = document.querySelector('#filmes')
let input = document.querySelector("#entrada")
let button = document.querySelector("#button")
let search = document.querySelector(".none")
let filmes = ['https://musicart.xboxlive.com/7/94fc5000-0000-0000-0000-000000000002/504/image.jpg', 'https://upload.wikimedia.org/wikipedia/pt/thumb/1/1b/Schoolrockposter.jpg/210px-Schoolrockposter.jpg', 'https://br.web.img2.acsta.net/pictures/15/10/14/14/58/220036.jpg', 'https://m.media-amazon.com/images/M/MV5BYTlhNzJjYzYtNGU3My00ZDI5LTgzZDUtYzllYjU1ZmU0YTgwXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_.jpg', 'https://m.media-amazon.com/images/M/MV5BYmQzNWMyNzQtODUyMC00ZjQzLWI3MDctYWY2YjhhNTg1YzRlXkEyXkFqcGdeQXVyMTEzMjQ4NzEw._V1_.jpg', 'https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_.jpg', 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d4/Uncharted_Official_Poster.jpg/220px-Uncharted_Official_Poster.jpg', 'https://upload.wikimedia.org/wikipedia/pt/1/1a/O_Jogo_da_Imita%C3%A7%C3%A3o.jpg', 'https://images-na.ssl-images-amazon.com/images/S/pv-target-images/1c6f7b64cde8450a55be8c5f8e74367736119134f2dc2f593fdd78f56044c254._RI_V_TTW_.jpg', 'https://vejasp.abril.com.br/wp-content/uploads/2016/12/hobbitposter.jpeg', 'https://m.media-amazon.com/images/M/MV5BMjE5MjkwODI3Nl5BMl5BanBnXkFtZTcwNjcwMDk4NA@@._V1_.jpg']
let nomes = ['Homem-aranhano Aranhaverso', 'Escola de Rock', 'Creed', 'Mulher Maravilha - 1984', 'The witches', '1917', 'Uncharted', 'O jogo da Imitação', 'Kingsman 2', 'Hobbit', 'Piratas do Caribe']
let descricao = ['Bitten by a radioactive spider in the subway, Brooklyn teenager Miles Morales suddenly develops mysterious powers that transform him into the one and only Spider-Man.', 'Overly enthusiastic guitarist Dewey Finn (Jack Black) gets thrown out of his bar band and finds himself in desperate need of work. Posing as a substitute music teacher at an elite private elementary school, he exposes his students to the hard rock gods he idolizes and emulates', 'Adonis Johnson (Michael B. Jordan) never knew his famous father, boxing champion Apollo Creed, who died before Adonis was born. However, boxing is in his blood, so he seeks out Rocky Balboa (Sylvester Stallone) and asks the retired champ to be his trainer', "Diana Prince lives quietly among mortals in the vibrant, sleek 1980s -- an era of excess driven by the pursuit of having it all. Though she's come into her full powers, she maintains a low profile by curating ancient artifacts, and only performing heroic acts incognito", 'In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort', 'During World War I, two British soldiers -- Lance Cpl. Schofield and Lance Cpl. Blake -- receive seemingly impossible orders. In a race against time, they must cross over into enemy territory to deliver a message', 'Treasure hunter Victor "Sully" Sullivan recruits street-smart Nathan Drake to help him recover a 500-year-old lost fortune amassed by explorer Ferdinand Magellan.', "In 1939, newly created British intelligence agency MI6 recruits Cambridge mathematics alumnus Alan Turing (Benedict Cumberbatch) to crack Nazi codes, including Enigma -- which cryptanalysts had thought unbreakable. Turing's team, including Joan Clarke (Keira Knightley), analyze Enigma messages while he builds a machine to decipher them", 'With their headquarters destroyed and the world held hostage, members of Kingsman find new allies when they discover a spy organization in the United States known as Statesman', 'Capt. Jack Sparrow (Johnny Depp) arrives at Port Royal in the Caribbean without a ship or crew. His timing is inopportune, however, because later that evening the town is besieged by a pirate ship']

//adiciona os filmes
for(let i = 0; i < filmes.length; i++){
    document.write("<div class='filme_img'><img src='" + filmes[i] + "'><h3>  " + nomes[i] + "</h3> </div>")
  
    button.addEventListener('click', ()=>{
        if(input.value == nomes[i]){
            html.innerHTML = "<div class='filme_img'><img src='" + filmes[i] + "'><h2> " + nomes[i] + " </h2><br> Descrição: " + descricao[i] + " </div>"
    
        }  else if(input.value == 0){
            search.innerHTML = ("<h1>Sem descrição</h1> </div>")
        }
    })
}
